### ISSUE TITLE
[feature] rank "unique snowflakes" higher

### ISSUE THREAD

**Issue by akavel** [maruel/panicparse#23]
after #3, it would be nice if goroutines with only 1 occurrence were ranked higher than merged (>1) ones. I think there's slightly higher probability that they may contain something "distinct" than the merged ones. Even if not, keeping some order in the traces could help grasp their nature. (Unless there's already some important ordering I didn't notice?)

Also, it would be nice if the "sections" in output could be somewhat "marked" then. I didn't realize the sorting is done with some meaningful order (i.e. #3) until I browsed through the issues. What I mean is for example something like:

```
---- SOURCE ---- [or: CULPRIT?]
1: running ...
  ...
---- USER, UNIQUE ----
1: ...
  ...
1: ...
  ...
---- USER, REPEATING ----
5: ...
  ...
22: ...
  ...
434: ...
  ...
---- STDLIB ----
1: ...
  ...
23: ...
 ...
```

**Comment by maruel** [comment]
The first routine showed is always the first routine printed out in the stack trace. This is because it is the one that was live when the panic or runtime error occurred.

The rest of the grouping _is_ weighted on the amount of stdlib in the stack trace, so I'm not sure what you are requesting here.

https://godoc.org/github.com/maruel/panicparse/stack#Stack.Less is the actual implementation. Probably worth improving the documentation to clarify the behavior. I'd accept a PR with that regard.

**Comment by akavel** [comment]
I'm mostly conflating 2 proposals in one ticket:

- part 1 is mostly what you said about improving documentation, or adding "section headers" in output;
- part 2 (what I really wanted to write/propose here) is: to sort "unique" stacktraces higher than "merged" stacktraces. In other words, stacktraces starting with `1:` would rank/sort higher than stacktraces starting with `55:`.

Does that make things somewhat more clear? Or not yet?

**Comment by maruel** [comment]
Can you address the first part first via a PR, then we can address the second part?

**Comment by maruel** [comment]
Closing due to lack of reply from the reporter.
