### ISSUE TITLE
Mark $GOPATH/pkg/mod and vendor packages distinctively

### ISSUE THREAD

**Issue by akavel** [maruel/panicparse#26]
Could the stdlib entries be marked visually in some way that would make it easy to clearly separate them from "my code" from the first glance? there's usually kinda... notable difference in quality/trust level between those groups :) I think either different color, or some marker chars at start of a line? personally, I'm also not quite sure if I see value in marking private vs. public identifiers using different color; but I assume you had a need for that.

Hm; truth said, it could also be nice if 3rd-party libs were marked with a distinct color/marker, too... but then detection can be difficult here: one has them in .../vendor/..., other in ../Godeps/..., other in "everything except $GOPATH/mycompany.com/... and $GOROOT/src/...". So maybe some kinda _$HOME/.config/panicparse/colors.ini_ with regexp->color patterns?... [with some option to specify complex matches like "everything except _this_ and _that_"?]

Poorly defined idea, I know, sorry...

**Comment by maruel** [comment]
stdlib _is_ handled distinctively, it's green instead of red by default.

Vendored packages is another thing, and I think it would be a good idea to add smart coloring based on that. No need for configuration, just look for a few known keyword in the path.

This requires updating https://godoc.org/github.com/maruel/panicparse/stack#Palette with the new detected type, then update the default palette. Please send a PR to add this. This is a breaking change.

Thanks

**Comment by akavel** [comment]
Argh, then it must be my color-blindness red<->green :(

As to vendored/non-vendored, I tried also to explain one more case, which isn't really vendored/non-vendored. I mean situation when one's *not* using vendoring, but still wants to mark "his" project differently than "third-party" projects. For example, let's say app *github.com/maruel/A* imports *github.com/maruel/B* and *github.com/someone/C* and *github.com/else/D*. When hacking on *github.com/maruel/A*, one would most probably want *github.com/maruel/A* and *github.com/maruel/B* highlighted in one color, while *github.com/someone/C* and *github.com/else/D* in a different color.

**Comment by maruel** [comment]
About red<->green color blindness, I recommend fine tuning your terminal to increase the visible delta between the two ANSI colors in issue #11 . I specifically chose the standard ANSI colors so you can override them more easily. The other option is to use a custom palette, that's why I made is configurable in the code; I didn't want to add a configuration file yet, as this means both future and backward compatibility, which I didn't want to commit to (yet).

Vendoring can be almost unambiguously detected; a "primary project" is much more fuzzy in its definition. That's why I'd recommend focusing on the vendoring part first, then the second part can be discussed. I don't want to go overboard with classification.

**Comment by maruel** [comment]
Focusing this issue on vendoring specifically, since this is the most actionable part of this feature request.

**Comment by maruel** [comment]
Broadening for go modules in $GOPATH/pkg/mod too.

**Comment by maruel** [comment]
So if anyone wants to tackle this, all the underlying code that does the analysis is there already. 

See https://github.com/maruel/panicparse/tree/master/internal/ui.go
and https://github.com/maruel/panicparse/blob/master/internal/htmlstack/goroutines.tpl.
