### ISSUE TITLE
Replace panic with panicparse within app?

### ISSUE THREAD

**Issue by jadbox** [maruel/panicparse#37]
Is there a way to bake panicparse into my app so that I just get the PP output, instead of having to run a command line tool every time I get a panic from one of my services?

**Comment by TrueFurby** [comment]
Use this package [stack](https://godoc.org/github.com/maruel/panicparse/stack). See the example for more info.

**Comment by maruel** [comment]
Thanks @TrueFurby, that's the solution for a programatic way to process output.

To better understand this request, @jadbox, am I understanding correctly that you want to have your app to generate a processed panic output? If so, this would need to live inside the stdlib, and the processing is a tad too involved to be safe to do inside the panic handler, which would mean loosing the trickiest panics, which makes the whole point moot.

The best solution is still to wrap your process with a separate process, pp, mainly, so that it is trapped as an external process. As @TrueFurby noted, you could implement your own process, which would send the processed stack to your monitoring service instead of the raw one.

**Comment by maruel** [comment]
Closing. Please comment if I misunderstood your request.
