### ISSUE TITLE
Successor

### ISSUE THREAD

**Issue by snwfdhmp** [maruel/panicparse#43]
Project continues [here](https://github.com/snwfdhmp/errlog). Featuring : 

- Clear stack trace
- Failing line recognition and highlighting

<img width="999" alt="capture d ecran 2019-02-20 a 15 34 39" src="https://user-images.githubusercontent.com/23099246/53104477-b9e46980-352f-11e9-9474-5a5bc6b38c38.png">

**Comment by maruel** [comment]
I don't understand, is it a request for collaboration, an ad or something else?

**Comment by snwfdhmp** [comment]
I thought you were not maintaining this repo anymore, this issue was intended to drive traffic of people looking for still a maintained package adding some more features. I have to say I'm a little ashamed by these practice but I'm seeking hard for attention.
I would be very happy to start collaborating with you on some development tools. Please tell me if one of my projects is interesting for us to start collaborating.

**Comment by maruel** [comment]
panicparse is maintained. The last commit is from August but it's just that I didn't have any external contribution since, and it's working well for my needs.

I do have local branches for new features but these are complex and didn't have time to polish them yet. I can't afford to push half-done things, as there's *over 700 clones per day*.

If you want to increase the reach of your projects, there are many ways to achieve this but spamming on other repositories is not a good way to make friends. If you want to contribute features on panicparse, filing an issue here is the right way, otherwise I'll have to ask you to look elsewhere.

Thanks

**Comment by snwfdhmp** [comment]
I understand. Please excuse me for my inconvenience.
