### ISSUE TITLE
Golang API to print from another applet?

### ISSUE THREAD

**Issue by pnegahdar** [maruel/panicparse#55]
I stitched together a little api to print from a go process (as part of error handlers in an application). 

Source here: https://github.com/pnegahdar/ppstack

Is this the best way to do this? I basically took a bunch of your things from `internal` and wrapped it in a small lib. Maybe this sort of functionality should be supported by panicparse? 

Happy to merge the work in and get rid of the project if you have a path forward.

**Comment by maruel** [comment]
Hi!

If it works for you you should keep it that way. I did not want to create such library because I did not want to maintain it, that's why this code is intentionally in internal/ and is relatively easy to copy-paste. This is working as intended. This is totally reasonable to create your own package exposing similar functionality and then version it properly with git tags. It's just not something I had the energy to maintain for the next decade as I was not satisfied with the API.

**Comment by pnegahdar** [comment]
Ah okay. No problem!

Thanks for your work on this package! It was very helpful :)

**Comment by maruel** [comment]
Thanks! Glad you're able to leverage it.
